package maps

import (
	"github.com/opengovern/og-describer-template/discovery/pkg/es"
)

var ResourceTypesToTables = map[string]string{
  "Github/Actions/Artifact": "github_actions_artifact",
  "Github/Actions/Runner": "github_actions_runner",
  "Github/Actions/Secret": "github_actions_secret",
  "Github/Actions/WorkflowRun": "github_actions_workflow_run",
  "Github/Branch": "github_branch",
  "Github/Branch/Protection": "github_branch_protection",
  "Github/Commit": "github_commit",
  "Github/Issue": "github_issue",
  "Github/License": "github_license",
  "Github/Organization": "github_organization",
  "Github/Organization/Collaborator": "github_organization_collaborator",
  "Github/Organization/Dependabot/Alert": "github_organization_dependabot_alert",
  "Github/Organization/Member": "github_organization_member",
  "Github/Organization/Team": "github_organization_team",
  "Github/PullRequest": "github_pull_request",
  "Github/Release": "github_release",
  "Github/Repository": "github_repository",
  "Github/Repository/Collaborator": "github_repository_collaborator",
  "Github/Repository/DependabotAlert": "github_repository_dependabot_alert",
  "Github/Repository/Deployment": "github_repository_deployment",
  "Github/Repository/Environment": "github_repository_environment",
  "Github/Repository/Ruleset": "github_repository_ruleset",
  "Github/Repository/SBOM": "github_repository_sbom",
  "Github/Repository/VulnerabilityAlert": "github_repository_vulnerability_alert",
  "Github/Tag": "github_tag",
  "Github/Team/Member": "github_team_member",
  "Github/User": "github_user",
  "Github/Workflow": "github_workflow",
  "Github/Container/Package": "github_container_package",
  "Github/Package/Maven": "github_maven_package",
  "Github/NPM/Package": "github_npm_package",
  "Github/Nuget/Package": "github_nuget_package",
  "Github/Artifact/DockerFile": "github_artifact_dockerfile",
}

var ResourceTypeToDescription = map[string]interface{}{
  "Github/Actions/Artifact": opengovernance.Artifact{},
  "Github/Actions/Runner": opengovernance.Runner{},
  "Github/Actions/Secret": opengovernance.Secret{},
  "Github/Actions/WorkflowRun": opengovernance.WorkflowRun{},
  "Github/Branch": opengovernance.Branch{},
  "Github/Branch/Protection": opengovernance.BranchProtection{},
  "Github/Commit": opengovernance.Commit{},
  "Github/Issue": opengovernance.Issue{},
  "Github/License": opengovernance.License{},
  "Github/Organization": opengovernance.Organization{},
  "Github/Organization/Collaborator": opengovernance.OrgCollaborators{},
  "Github/Organization/Dependabot/Alert": opengovernance.OrgAlertDependabot{},
  "Github/Organization/Member": opengovernance.OrgMembers{},
  "Github/Organization/Team": opengovernance.Team{},
  "Github/PullRequest": opengovernance.PullRequest{},
  "Github/Release": opengovernance.Release{},
  "Github/Repository": opengovernance.Repository{},
  "Github/Repository/Collaborator": opengovernance.RepoCollaborators{},
  "Github/Repository/DependabotAlert": opengovernance.RepoAlertDependabot{},
  "Github/Repository/Deployment": opengovernance.RepoDeployment{},
  "Github/Repository/Environment": opengovernance.RepoEnvironment{},
  "Github/Repository/Ruleset": opengovernance.RepoRuleSet{},
  "Github/Repository/SBOM": opengovernance.RepoSBOM{},
  "Github/Repository/VulnerabilityAlert": opengovernance.RepoVulnerabilityAlert{},
  "Github/Tag": opengovernance.Tag{},
  "Github/Team/Member": opengovernance.TeamMembers{},
  "Github/User": opengovernance.User{},
  "Github/Workflow": opengovernance.Workflow{},
  "Github/Container/Package": opengovernance.ContainerPackage{},
  "Github/Package/Maven": opengovernance.PackageDetail{},
  "Github/NPM/Package": opengovernance.PackageDetail{},
  "Github/Nuget/Package": opengovernance.Package{},
  "Github/Artifact/DockerFile": opengovernance.ArtifactDockerFile{},
}

var TablesToResourceTypes = map[string]string{
  "github_actions_artifact": "Github/Actions/Artifact",
  "github_actions_runner": "Github/Actions/Runner",
  "github_actions_secret": "Github/Actions/Secret",
  "github_actions_workflow_run": "Github/Actions/WorkflowRun",
  "github_branch": "Github/Branch",
  "github_branch_protection": "Github/Branch/Protection",
  "github_commit": "Github/Commit",
  "github_issue": "Github/Issue",
  "github_license": "Github/License",
  "github_organization": "Github/Organization",
  "github_organization_collaborator": "Github/Organization/Collaborator",
  "github_organization_dependabot_alert": "Github/Organization/Dependabot/Alert",
  "github_organization_member": "Github/Organization/Member",
  "github_organization_team": "Github/Organization/Team",
  "github_pull_request": "Github/PullRequest",
  "github_release": "Github/Release",
  "github_repository": "Github/Repository",
  "github_repository_collaborator": "Github/Repository/Collaborator",
  "github_repository_dependabot_alert": "Github/Repository/DependabotAlert",
  "github_repository_deployment": "Github/Repository/Deployment",
  "github_repository_environment": "Github/Repository/Environment",
  "github_repository_ruleset": "Github/Repository/Ruleset",
  "github_repository_sbom": "Github/Repository/SBOM",
  "github_repository_vulnerability_alert": "Github/Repository/VulnerabilityAlert",
  "github_tag": "Github/Tag",
  "github_team_member": "Github/Team/Member",
  "github_user": "Github/User",
  "github_workflow": "Github/Workflow",
  "github_container_package": "Github/Container/Package",
  "github_maven_package": "Github/Package/Maven",
  "github_npm_package": "Github/NPM/Package",
  "github_nuget_package": "Github/Nuget/Package",
  "github_artifact_dockerfile": "Github/Artifact/DockerFile",
}
